//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupOptimaToolkit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDN_Prezentacja_KHEntities : DbContext
    {
        public CDN_Prezentacja_KHEntities()
            : base("name=CDN_Prezentacja_KHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kontrahenci> Kontrahencis { get; set; }
        public virtual DbSet<TraNag> TraNags { get; set; }
    }
}
